---
title: "Untitled"
author: "Jamie Ponmattam"
date: "2025-01-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


options(scipen = 99999)

library(tidyverse)
library(data.table)
library(lubridate)
library(haven)
library(openxlsx)
library(combinat)
library(Hmisc)
```



# LE at BIRTH
```{r}
path.in <- "00_data/cleaned_life table"
file <- list.files(path.in, full.names = TRUE, pattern = ".csv")
df.dat <- bind_rows(lapply(file, function(x) fread(x) %>% 
                             select(Sex, Region, ISO3, Age, Year, Type, `Expectation of life e(x)`)  %>%
                             filter(Type == "Country/Area") %>%
                             filter(Age == 65 | Age == "65") %>%
                             mutate(Age = as.numeric(Age),
                                    e65 = as.numeric(`Expectation of life e(x)`)) %>%
                             select(-`Expectation of life e(x)`) %>%
                             filter(Year %in% c(1950, 2019)) )) %>%
  filter(Sex == "Both") 



file.g.inc <- paste0("02_outputs/01a_PREP_01_categories_INCOME_1950_2019.csv")
df.iso3 <- fread(file.g.inc) %>%
  rename(ISO3 = Country)%>%
  rename(Year = year) 

df.iso3.1950same <- df.iso3 %>%
  pivot_wider(names_from = Year,
              values_from = group)  %>%
  filter(`1950` == `2019`) %>%
  pivot_longer(names_to = "Year",
               values_to = "group",
               cols = 2:3) %>%
  mutate(Year = as.numeric(Year))



file.p <- paste0("02_outputs/01c_PREP_03_px_1950_2019.csv")
df.pop <- fread(file.p)
df.pop.final <- df.pop %>%
  pivot_longer(names_to = "age_group",
               values_to = "pop",  
               cols = 4:25)  %>%
  filter(age_group %in% c("p65-69", "p70-74", "p75-79", "p80-84",
                          "p85-89", "p90-94" ,"p95-99", "p100+")) %>%
  group_by(Sex, Country, Year) %>% 
  summarise(pop = sum(pop)) %>%
  ungroup() %>%
  filter(Year %in% c(1950, 2019))






df.dat <- right_join(df.dat, df.iso3.1950same) %>%
  filter(!ISO3 %in% c("CSK", "YUG"))



df.dat.ISO3 <- df.dat %>%
  full_join(., df.pop.final, by = c("Sex", "Year", "ISO3" = "Country")) %>%
  filter(Type == "Country/Area") %>%
  pivot_wider(names_from = Year,
              values_from = c(e65, pop)) %>%
  filter(!is.na(group))



```


```{r}
file <- paste0("02_outputs/Table_02c_LE65_1950 cat_no change.xlsx")

ls.df <- list(df.dat.ISO3)
names(ls.df) <- c("ISO3_LE")

write.xlsx(ls.df, file)
```
